#nullable enable
using System;
namespace BattleSystemECS.Core
{
    /// <summary>生产 group binder 的独立 typed 合同事实，运行期不读取 manifest 或 catalog。</summary>
    internal static class FrameBindingFacts
    {
        private static readonly string[] DisabledNodeIds = new[] { "ai.enemy-affix.update", "ai.lifesteal.prepare", "ai.lifesteal.update", "build.tower-income.update", "build.tower-relocate.update", "combat-setup.heat.prepare", "combat-setup.link.prepare", "combat-setup.overcharge.prepare", "combat.beam.update", "combat.demolish.update", "combat.dispel.update", "combat.enemy-projectile.update", "combat.energy.update", "combat.heat.update", "combat.link.update", "combat.overcharge.update", "combat.silence.update", "movement.enemy-healer.prepare", "movement.enemy-healer.update", "movement.steal-gold.update", "movement.summon.prepare", "movement.summon.update", "movement.wound.prepare", "movement.wound.update", "post-death.life-link.resolve", "post-death.tower-income.update", "pregame.construction.update", "spatial.fog.prepare", "spatial.fog.update", "spatial.patrol.prepare", "spatial.patrol.update", "spatial.point-defense.prepare", "spatial.point-defense.update" };
        internal static FrameBindingRegistration Get(string nodeId)
        {
            if (!TryGet(nodeId, out var registration))
                throw new FrameGraphValidationException("Unknown production frame binding fact: " + nodeId);
            return registration;
        }

        internal static bool TryGet(string nodeId, out FrameBindingRegistration registration)
        {
            switch (nodeId)
            {
                case "pregame.wave.read-current-wave": registration = new FrameBindingRegistration("pregame.wave.read-current-wave","WaveSpawning",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.WaveSpawning"},Array.Empty<string>()); return true;
                case "pregame.wave.read-current-level": registration = new FrameBindingRegistration("pregame.wave.read-current-level","WaveSpawning",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.WaveSpawning"},Array.Empty<string>()); return true;
                case "spawning.wave.update": registration = new FrameBindingRegistration("spawning.wave.update","WaveSpawning",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.WaveSpawning"},Array.Empty<string>()); return true;
                case "spawning.wave.callback-dispatch": registration = new FrameBindingRegistration("spawning.wave.callback-dispatch","WaveSpawning",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.WaveSpawning"},Array.Empty<string>()); return true;
                case "spawning.nest.prepare": registration = new FrameBindingRegistration("spawning.nest.prepare","Nest",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.Nest"},Array.Empty<string>()); return true;
                case "spawning.nest.update": registration = new FrameBindingRegistration("spawning.nest.update","Nest",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Nest"},Array.Empty<string>()); return true;
                case "build.gold.update": registration = new FrameBindingRegistration("build.gold.update","Gold",FramePhaseMask.Build,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Gold"},Array.Empty<string>()); return true;
                case "build.upgrade.update": registration = new FrameBindingRegistration("build.upgrade.update","Upgrade",FramePhaseMask.Build,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Upgrade"},Array.Empty<string>()); return true;
                case "build.interest.update": registration = new FrameBindingRegistration("build.interest.update","Interest",FramePhaseMask.Build,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Interest"},Array.Empty<string>()); return true;
                case "build.skill.update": registration = new FrameBindingRegistration("build.skill.update","Skill",FramePhaseMask.Build,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Skill"},Array.Empty<string>()); return true;
                case "build.skill.reject-pending": registration = new FrameBindingRegistration("build.skill.reject-pending","Skill",FramePhaseMask.Build,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Skill"},Array.Empty<string>()); return true;
                case "combat-setup.skill.prepare": registration = new FrameBindingRegistration("combat-setup.skill.prepare","Skill",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.Skill"},Array.Empty<string>()); return true;
                case "skill-buff.skill.resolve-damage": registration = new FrameBindingRegistration("skill-buff.skill.resolve-damage","Skill",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Skill"},Array.Empty<string>()); return true;
                case "skill-buff.skill.update": registration = new FrameBindingRegistration("skill-buff.skill.update","Skill",FramePhaseMask.Wave,FrameExecutionSemantics.InternalParallelCollectSerialCommit,new[]{"ComponentStore","registration.Skill"},Array.Empty<string>()); return true;
                case "skill-buff.buff.update": registration = new FrameBindingRegistration("skill-buff.buff.update","Buff",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Buff"},Array.Empty<string>()); return true;
                case "skill-buff.buff.resolve-dot": registration = new FrameBindingRegistration("skill-buff.buff.resolve-dot","Buff",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Buff"},Array.Empty<string>()); return true;
                case "skill-buff.elemental.update": registration = new FrameBindingRegistration("skill-buff.elemental.update","ElementalReaction",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.ElementalReaction"},Array.Empty<string>()); return true;
                case "skill-buff.elemental.resolve": registration = new FrameBindingRegistration("skill-buff.elemental.resolve","ElementalReaction",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.ElementalReaction"},Array.Empty<string>()); return true;
                case "post-death.combo.update": registration = new FrameBindingRegistration("post-death.combo.update","Combo",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Combo"},Array.Empty<string>()); return true;
                case "build.auto-skill.update": registration = new FrameBindingRegistration("build.auto-skill.update","AutoSkill",FramePhaseMask.Build,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.AutoSkill"},Array.Empty<string>()); return true;
                case "build.mana.update": registration = new FrameBindingRegistration("build.mana.update","Mana",FramePhaseMask.Build,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Mana"},Array.Empty<string>()); return true;
                case "combat-setup.mana.prepare": registration = new FrameBindingRegistration("combat-setup.mana.prepare","Mana",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Mana"},Array.Empty<string>()); return true;
                case "combat.mana.update": registration = new FrameBindingRegistration("combat.mana.update","Mana",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Mana"},Array.Empty<string>()); return true;
                case "build.mana-shield.update": registration = new FrameBindingRegistration("build.mana-shield.update","ManaShield",FramePhaseMask.Build,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.ManaShield"},Array.Empty<string>()); return true;
                case "combat.mana-shield.update": registration = new FrameBindingRegistration("combat.mana-shield.update","ManaShield",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.ManaShield"},Array.Empty<string>()); return true;
                case "build.global-skill.update": registration = new FrameBindingRegistration("build.global-skill.update","GlobalSkill",FramePhaseMask.Build,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.GlobalSkill"},Array.Empty<string>()); return true;
                case "combat-setup.global-skill.prepare": registration = new FrameBindingRegistration("combat-setup.global-skill.prepare","GlobalSkill",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.GlobalSkill"},Array.Empty<string>()); return true;
                case "combat.global-skill.update": registration = new FrameBindingRegistration("combat.global-skill.update","GlobalSkill",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.GlobalSkill"},Array.Empty<string>()); return true;
                case "skill-buff.mark.update": registration = new FrameBindingRegistration("skill-buff.mark.update","Mark",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Mark"},Array.Empty<string>()); return true;
                case "skill-buff.death-mark.update": registration = new FrameBindingRegistration("skill-buff.death-mark.update","DeathMark",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.DeathMark"},Array.Empty<string>()); return true;
                case "combat.culling.update": registration = new FrameBindingRegistration("combat.culling.update","Culling",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Culling"},Array.Empty<string>()); return true;
                case "pregame.time-rewind.update": registration = new FrameBindingRegistration("pregame.time-rewind.update","TimeRewind",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.TimeRewind"},Array.Empty<string>()); return true;
                case "combat-setup.tower-attack.prepare": registration = new FrameBindingRegistration("combat-setup.tower-attack.prepare","TowerAttack",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.TowerAttack"},Array.Empty<string>()); return true;
                case "combat.tower-attack.update": registration = new FrameBindingRegistration("combat.tower-attack.update","TowerAttack",FramePhaseMask.Wave,FrameExecutionSemantics.InternalParallelCollectSerialCommit,new[]{"ComponentStore","registration.TowerAttack"},Array.Empty<string>()); return true;
                case "combat-setup.synergy.prepare": registration = new FrameBindingRegistration("combat-setup.synergy.prepare","TowerSynergy",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.TowerSynergy"},Array.Empty<string>()); return true;
                case "combat.synergy.resolve-buff-shares": registration = new FrameBindingRegistration("combat.synergy.resolve-buff-shares","TowerSynergy",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.TowerSynergy"},Array.Empty<string>()); return true;
                case "combat.synergy.update": registration = new FrameBindingRegistration("combat.synergy.update","TowerSynergy",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.TowerSynergy"},Array.Empty<string>()); return true;
                case "combat-setup.fortress.prepare": registration = new FrameBindingRegistration("combat-setup.fortress.prepare","TowerFortress",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.TowerFortress"},Array.Empty<string>()); return true;
                case "combat.bloodlust.update": registration = new FrameBindingRegistration("combat.bloodlust.update","Bloodlust",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Bloodlust"},Array.Empty<string>()); return true;
                case "build.pre-fight-buff.update": registration = new FrameBindingRegistration("build.pre-fight-buff.update","PreFightBuff",FramePhaseMask.Build,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.PreFightBuff"},Array.Empty<string>()); return true;
                case "combat.momentum.update": registration = new FrameBindingRegistration("combat.momentum.update","Momentum",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Momentum"},Array.Empty<string>()); return true;
                case "combat.adrenaline.update": registration = new FrameBindingRegistration("combat.adrenaline.update","Adrenaline",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Adrenaline"},Array.Empty<string>()); return true;
                case "combat.crest.update": registration = new FrameBindingRegistration("combat.crest.update","Crest",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Crest"},Array.Empty<string>()); return true;
                case "combat.tower-morph.update": registration = new FrameBindingRegistration("combat.tower-morph.update","TowerMorph",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.TowerMorph"},Array.Empty<string>()); return true;
                case "combat-setup.aura.prepare": registration = new FrameBindingRegistration("combat-setup.aura.prepare","AuraTower",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.AuraTower"},Array.Empty<string>()); return true;
                case "combat.aura.resolve": registration = new FrameBindingRegistration("combat.aura.resolve","AuraTower",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.AuraTower"},Array.Empty<string>()); return true;
                case "combat-setup.curse.prepare": registration = new FrameBindingRegistration("combat-setup.curse.prepare","Curse",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.Curse"},Array.Empty<string>()); return true;
                case "combat.curse.resolve": registration = new FrameBindingRegistration("combat.curse.resolve","Curse",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Curse"},Array.Empty<string>()); return true;
                case "combat-setup.pull-tower.prepare": registration = new FrameBindingRegistration("combat-setup.pull-tower.prepare","PullTower",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.PullTower"},Array.Empty<string>()); return true;
                case "combat.pull-tower.update": registration = new FrameBindingRegistration("combat.pull-tower.update","PullTower",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.PullTower"},Array.Empty<string>()); return true;
                case "combat-setup.taunt.prepare": registration = new FrameBindingRegistration("combat-setup.taunt.prepare","Taunt",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.Taunt"},Array.Empty<string>()); return true;
                case "combat.taunt.resolve": registration = new FrameBindingRegistration("combat.taunt.resolve","Taunt",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Taunt"},Array.Empty<string>()); return true;
                case "skill-buff.bleed.update": registration = new FrameBindingRegistration("skill-buff.bleed.update","Bleed",FramePhaseMask.Wave,FrameExecutionSemantics.ParallelDisjointWrite,new[]{"ComponentStore","registration.Bleed"},Array.Empty<string>()); return true;
                case "skill-buff.bleed.resolve": registration = new FrameBindingRegistration("skill-buff.bleed.resolve","Bleed",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Bleed"},Array.Empty<string>()); return true;
                case "skill-buff.frostbite.update": registration = new FrameBindingRegistration("skill-buff.frostbite.update","Frostbite",FramePhaseMask.Wave,FrameExecutionSemantics.ParallelDisjointWrite,new[]{"ComponentStore","registration.Frostbite"},Array.Empty<string>()); return true;
                case "skill-buff.frostbite.resolve": registration = new FrameBindingRegistration("skill-buff.frostbite.resolve","Frostbite",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Frostbite"},Array.Empty<string>()); return true;
                case "skill-buff.heal-aura.prepare": registration = new FrameBindingRegistration("skill-buff.heal-aura.prepare","HealAura",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.HealAura"},Array.Empty<string>()); return true;
                case "skill-buff.heal-aura.update": registration = new FrameBindingRegistration("skill-buff.heal-aura.update","HealAura",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.HealAura"},Array.Empty<string>()); return true;
                case "skill-buff.thorns-aura.prepare": registration = new FrameBindingRegistration("skill-buff.thorns-aura.prepare","ThornsAura",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.ThornsAura"},Array.Empty<string>()); return true;
                case "skill-buff.thorns-aura.update": registration = new FrameBindingRegistration("skill-buff.thorns-aura.update","ThornsAura",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.ThornsAura"},Array.Empty<string>()); return true;
                case "skill-buff.rally.update": registration = new FrameBindingRegistration("skill-buff.rally.update","Rally",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Rally"},Array.Empty<string>()); return true;
                case "combat.tower-active-skill.update": registration = new FrameBindingRegistration("combat.tower-active-skill.update","TowerActiveSkill",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.TowerActiveSkill"},Array.Empty<string>()); return true;
                case "combat.aggro.update": registration = new FrameBindingRegistration("combat.aggro.update","Aggro",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Aggro"},Array.Empty<string>()); return true;
                case "combat.echo-clone.update": registration = new FrameBindingRegistration("combat.echo-clone.update","EchoClone",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.EchoClone"},Array.Empty<string>()); return true;
                case "combat.projectile.update": registration = new FrameBindingRegistration("combat.projectile.update","Projectile",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Projectile"},Array.Empty<string>()); return true;
                case "spatial.chrono.prepare": registration = new FrameBindingRegistration("spatial.chrono.prepare","ChronoTower",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.ChronoTower"},Array.Empty<string>()); return true;
                case "spatial.chrono.update": registration = new FrameBindingRegistration("spatial.chrono.update","ChronoTower",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.ChronoTower"},Array.Empty<string>()); return true;
                case "spatial.mine.prepare": registration = new FrameBindingRegistration("spatial.mine.prepare","Mine",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Mine"},Array.Empty<string>()); return true;
                case "spatial.mine.update": registration = new FrameBindingRegistration("spatial.mine.update","Mine",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Mine"},Array.Empty<string>()); return true;
                case "combat.shrine.prepare": registration = new FrameBindingRegistration("combat.shrine.prepare","TowerShrine",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.TowerShrine"},Array.Empty<string>()); return true;
                case "combat.shrine.resolve": registration = new FrameBindingRegistration("combat.shrine.resolve","TowerShrine",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.TowerShrine"},Array.Empty<string>()); return true;
                case "combat.beacon.prepare": registration = new FrameBindingRegistration("combat.beacon.prepare","TowerBeacon",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.TowerBeacon"},Array.Empty<string>()); return true;
                case "combat.beacon.resolve": registration = new FrameBindingRegistration("combat.beacon.resolve","TowerBeacon",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.TowerBeacon"},Array.Empty<string>()); return true;
                case "combat-setup.player-attack.prepare": registration = new FrameBindingRegistration("combat-setup.player-attack.prepare","PlayerTowerAttack",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.PlayerTowerAttack"},Array.Empty<string>()); return true;
                case "combat.player-attack.update": registration = new FrameBindingRegistration("combat.player-attack.update","PlayerTowerAttack",FramePhaseMask.Wave,FrameExecutionSemantics.InternalParallelCollectSerialCommit,new[]{"ComponentStore","registration.PlayerTowerAttack"},Array.Empty<string>()); return true;
                case "combat-setup.hero.prepare": registration = new FrameBindingRegistration("combat-setup.hero.prepare","Hero",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.Hero"},Array.Empty<string>()); return true;
                case "combat.hero.update": registration = new FrameBindingRegistration("combat.hero.update","Hero",FramePhaseMask.Wave,FrameExecutionSemantics.InternalParallelCollectSerialCommit,new[]{"ComponentStore","registration.Hero"},Array.Empty<string>()); return true;
                case "combat.hero-skill.update": registration = new FrameBindingRegistration("combat.hero-skill.update","HeroSkill",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.HeroSkill"},Array.Empty<string>()); return true;
                case "movement.enemy.prepare": registration = new FrameBindingRegistration("movement.enemy.prepare","EnemyMovement",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.EnemyMovement"},Array.Empty<string>()); return true;
                case "movement.enemy.update": registration = new FrameBindingRegistration("movement.enemy.update","EnemyMovement",FramePhaseMask.Wave,FrameExecutionSemantics.InternalParallelCollectSerialCommit,new[]{"ComponentStore","registration.EnemyMovement"},Array.Empty<string>()); return true;
                case "ai.enemy.prepare": registration = new FrameBindingRegistration("ai.enemy.prepare","EnemyAI",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.EnemyAI"},Array.Empty<string>()); return true;
                case "ai.enemy.update": registration = new FrameBindingRegistration("ai.enemy.update","EnemyAI",FramePhaseMask.Wave,FrameExecutionSemantics.InternalParallelCollectSerialCommit,new[]{"ComponentStore","registration.EnemyAI"},Array.Empty<string>()); return true;
                case "ai.enemy-ability.prepare": registration = new FrameBindingRegistration("ai.enemy-ability.prepare","EnemyAbility",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.EnemyAbility"},Array.Empty<string>()); return true;
                case "ai.enemy-ability.cooldowns": registration = new FrameBindingRegistration("ai.enemy-ability.cooldowns","EnemyAbility",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.EnemyAbility"},Array.Empty<string>()); return true;
                case "ai.enemy-ability.execute": registration = new FrameBindingRegistration("ai.enemy-ability.execute","EnemyAbility",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.EnemyAbility"},Array.Empty<string>()); return true;
                case "ai.enemy-ability.cast-timers": registration = new FrameBindingRegistration("ai.enemy-ability.cast-timers","EnemyAbility",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.EnemyAbility"},Array.Empty<string>()); return true;
                case "ai.enemy-ability.update": registration = new FrameBindingRegistration("ai.enemy-ability.update","EnemyAbility",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.EnemyAbility"},Array.Empty<string>()); return true;
                case "post-death.fission.update": registration = new FrameBindingRegistration("post-death.fission.update","EnemyFission",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.EnemyFission"},Array.Empty<string>()); return true;
                case "terrain.enemy-morph.update": registration = new FrameBindingRegistration("terrain.enemy-morph.update","EnemyMorph",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.EnemyMorph"},Array.Empty<string>()); return true;
                case "ai.burrow.prepare": registration = new FrameBindingRegistration("ai.burrow.prepare","EnemyBurrow",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.EnemyBurrow"},Array.Empty<string>()); return true;
                case "ai.burrow.update": registration = new FrameBindingRegistration("ai.burrow.update","EnemyBurrow",FramePhaseMask.Wave,FrameExecutionSemantics.InternalParallelCollectSerialCommit,new[]{"ComponentStore","registration.EnemyBurrow"},Array.Empty<string>()); return true;
                case "ai.burrow.apply": registration = new FrameBindingRegistration("ai.burrow.apply","EnemyBurrow",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.EnemyBurrow"},Array.Empty<string>()); return true;
                case "ai.necromancer.prepare": registration = new FrameBindingRegistration("ai.necromancer.prepare","Necromancer",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.Necromancer"},Array.Empty<string>()); return true;
                case "ai.necromancer.update": registration = new FrameBindingRegistration("ai.necromancer.update","Necromancer",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Necromancer"},Array.Empty<string>()); return true;
                case "ai.life-link.prepare": registration = new FrameBindingRegistration("ai.life-link.prepare","LifeLink",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.LifeLink"},Array.Empty<string>()); return true;
                case "ai.life-link.update": registration = new FrameBindingRegistration("ai.life-link.update","LifeLink",FramePhaseMask.Wave,FrameExecutionSemantics.InternalParallelCollectSerialCommit,new[]{"ComponentStore","registration.LifeLink"},Array.Empty<string>()); return true;
                case "ai.life-link.cooldowns": registration = new FrameBindingRegistration("ai.life-link.cooldowns","LifeLink",FramePhaseMask.Wave,FrameExecutionSemantics.ParallelDisjointWrite,new[]{"ComponentStore","registration.LifeLink"},Array.Empty<string>()); return true;
                case "combat-setup.hit-shield.prepare": registration = new FrameBindingRegistration("combat-setup.hit-shield.prepare","HitShield",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.HitShield"},Array.Empty<string>()); return true;
                case "combat.hit-shield.update": registration = new FrameBindingRegistration("combat.hit-shield.update","HitShield",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.HitShield"},Array.Empty<string>()); return true;
                case "combat.sabotage.update": registration = new FrameBindingRegistration("combat.sabotage.update","TowerSabotage",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.TowerSabotage"},Array.Empty<string>()); return true;
                case "ai.mana-burn.prepare": registration = new FrameBindingRegistration("ai.mana-burn.prepare","ManaBurn",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.ManaBurn"},Array.Empty<string>()); return true;
                case "ai.mana-burn.update": registration = new FrameBindingRegistration("ai.mana-burn.update","ManaBurn",FramePhaseMask.Wave,FrameExecutionSemantics.InternalParallelCollectSerialCommit,new[]{"ComponentStore","registration.ManaBurn"},Array.Empty<string>()); return true;
                case "ai.phase.prepare": registration = new FrameBindingRegistration("ai.phase.prepare","Phase",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.Phase"},Array.Empty<string>()); return true;
                case "ai.phase.update": registration = new FrameBindingRegistration("ai.phase.update","Phase",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Phase"},Array.Empty<string>()); return true;
                case "ai.fear.prepare": registration = new FrameBindingRegistration("ai.fear.prepare","Fear",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.Fear"},Array.Empty<string>()); return true;
                case "ai.fear.update": registration = new FrameBindingRegistration("ai.fear.update","Fear",FramePhaseMask.Wave,FrameExecutionSemantics.ParallelDisjointWrite,new[]{"ComponentStore","registration.Fear"},Array.Empty<string>()); return true;
                case "ai.enemy-strafe.prepare": registration = new FrameBindingRegistration("ai.enemy-strafe.prepare","EnemyStrafe",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.EnemyStrafe"},Array.Empty<string>()); return true;
                case "ai.enemy-strafe.update": registration = new FrameBindingRegistration("ai.enemy-strafe.update","EnemyStrafe",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.EnemyStrafe"},Array.Empty<string>()); return true;
                case "combat.suicide-bomb.update": registration = new FrameBindingRegistration("combat.suicide-bomb.update","SuicideBomb",FramePhaseMask.Wave,FrameExecutionSemantics.InternalParallelCollectSerialCommit,new[]{"ComponentStore","registration.SuicideBomb"},Array.Empty<string>()); return true;
                case "combat.reflect.resolve": registration = new FrameBindingRegistration("combat.reflect.resolve","ReflectTower",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.ReflectTower"},Array.Empty<string>()); return true;
                case "combat.reflect.apply": registration = new FrameBindingRegistration("combat.reflect.apply","ReflectTower",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.ReflectTower"},Array.Empty<string>()); return true;
                case "combat.stealth.update": registration = new FrameBindingRegistration("combat.stealth.update","TowerStealth",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.TowerStealth"},Array.Empty<string>()); return true;
                case "movement.path-block.update": registration = new FrameBindingRegistration("movement.path-block.update","PathBlock",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.PathBlock"},Array.Empty<string>()); return true;
                case "build.desperation.update": registration = new FrameBindingRegistration("build.desperation.update","Desperation",FramePhaseMask.Build,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Desperation"},Array.Empty<string>()); return true;
                case "pregame.desperation.update": registration = new FrameBindingRegistration("pregame.desperation.update","Desperation",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Desperation"},Array.Empty<string>()); return true;
                case "build.shop-reroll.update": registration = new FrameBindingRegistration("build.shop-reroll.update","ShopReroll",FramePhaseMask.Build,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.ShopReroll"},Array.Empty<string>()); return true;
                case "terrain.prepare": registration = new FrameBindingRegistration("terrain.prepare","Terrain",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.Terrain"},Array.Empty<string>()); return true;
                case "terrain.update": registration = new FrameBindingRegistration("terrain.update","Terrain",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Terrain"},Array.Empty<string>()); return true;
                case "movement.pathfinding.prepare": registration = new FrameBindingRegistration("movement.pathfinding.prepare","Pathfinding",FramePhaseMask.Wave,FrameExecutionSemantics.ParallelDisjointWrite,new[]{"ComponentStore","registration.Pathfinding"},Array.Empty<string>()); return true;
                case "movement.deployable-trap.update": registration = new FrameBindingRegistration("movement.deployable-trap.update","DeployableTrap",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.DeployableTrap"},Array.Empty<string>()); return true;
                case "movement.path-modifier.prepare": registration = new FrameBindingRegistration("movement.path-modifier.prepare","PathModifier",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.PathModifier"},Array.Empty<string>()); return true;
                case "movement.path-modifier.update": registration = new FrameBindingRegistration("movement.path-modifier.update","PathModifier",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.PathModifier"},Array.Empty<string>()); return true;
                case "movement.pull.prepare": registration = new FrameBindingRegistration("movement.pull.prepare","Pull",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.Pull"},Array.Empty<string>()); return true;
                case "movement.pull.update": registration = new FrameBindingRegistration("movement.pull.update","Pull",FramePhaseMask.Wave,FrameExecutionSemantics.ParallelDisjointWrite,new[]{"ComponentStore","registration.Pull"},Array.Empty<string>()); return true;
                case "pregame.weather.update": registration = new FrameBindingRegistration("pregame.weather.update","Weather",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Weather"},Array.Empty<string>()); return true;
                case "pregame.day-night.update": registration = new FrameBindingRegistration("pregame.day-night.update","DayNight",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.DayNight"},Array.Empty<string>()); return true;
                case "terrain.wave-mutator.prepare": registration = new FrameBindingRegistration("terrain.wave-mutator.prepare","WaveMutator",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.WaveMutator"},Array.Empty<string>()); return true;
                case "terrain.wave-mutator.update": registration = new FrameBindingRegistration("terrain.wave-mutator.update","WaveMutator",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.WaveMutator"},Array.Empty<string>()); return true;
                case "pregame.random-event.update": registration = new FrameBindingRegistration("pregame.random-event.update","RandomEvent",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.RandomEvent"},Array.Empty<string>()); return true;
                case "pregame.random-event.callback-dispatch": registration = new FrameBindingRegistration("pregame.random-event.callback-dispatch","RandomEvent",FramePhaseMask.Wave,FrameExecutionSemantics.PresentationCommit,new[]{"ComponentStore","registration.RandomEvent"},Array.Empty<string>()); return true;
                case "spatial.telegraph.update": registration = new FrameBindingRegistration("spatial.telegraph.update","Telegraph",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Telegraph"},Array.Empty<string>()); return true;
                case "pregame.adaptive-difficulty.update": registration = new FrameBindingRegistration("pregame.adaptive-difficulty.update","AdaptiveDifficulty",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.AdaptiveDifficulty"},Array.Empty<string>()); return true;
                case "post-death.corpse.update": registration = new FrameBindingRegistration("post-death.corpse.update","CorpseEffect",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.CorpseEffect"},Array.Empty<string>()); return true;
                case "skill-buff.healing-zone.update": registration = new FrameBindingRegistration("skill-buff.healing-zone.update","HealingZone",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.HealingZone"},Array.Empty<string>()); return true;
                case "ai.zone-control.update": registration = new FrameBindingRegistration("ai.zone-control.update","ZoneControl",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.ZoneControl"},Array.Empty<string>()); return true;
                case "build.objective.update": registration = new FrameBindingRegistration("build.objective.update","Objective",FramePhaseMask.Build,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Objective"},Array.Empty<string>()); return true;
                case "post-death.objective.update": registration = new FrameBindingRegistration("post-death.objective.update","Objective",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Objective"},Array.Empty<string>()); return true;
                case "build.resource-node.update": registration = new FrameBindingRegistration("build.resource-node.update","ResourceNode",FramePhaseMask.Build,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.ResourceNode"},Array.Empty<string>()); return true;
                case "post-death.resource-node.update": registration = new FrameBindingRegistration("post-death.resource-node.update","ResourceNode",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.ResourceNode"},Array.Empty<string>()); return true;
                case "post-death.doom-clock.update": registration = new FrameBindingRegistration("post-death.doom-clock.update","DoomClock",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.DoomClock"},Array.Empty<string>()); return true;
                case "post-death.soul-harvest.update": registration = new FrameBindingRegistration("post-death.soul-harvest.update","SoulHarvest",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.SoulHarvest"},Array.Empty<string>()); return true;
                case "combat-setup.hot-zone.prepare": registration = new FrameBindingRegistration("combat-setup.hot-zone.prepare","HotZone",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.HotZone"},Array.Empty<string>()); return true;
                case "combat-setup.terrain-zone.prepare": registration = new FrameBindingRegistration("combat-setup.terrain-zone.prepare","TerrainZone",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.TerrainZone"},Array.Empty<string>()); return true;
                case "combat-setup.terrain-zone.update": registration = new FrameBindingRegistration("combat-setup.terrain-zone.update","TerrainZone",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.TerrainZone"},Array.Empty<string>()); return true;
                case "combat-setup.frost-zone.prepare": registration = new FrameBindingRegistration("combat-setup.frost-zone.prepare","FrostZone",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.FrostZone"},Array.Empty<string>()); return true;
                case "combat-setup.frost-zone.update": registration = new FrameBindingRegistration("combat-setup.frost-zone.update","FrostZone",FramePhaseMask.Wave,FrameExecutionSemantics.ParallelDisjointWrite,new[]{"ComponentStore","registration.FrostZone"},Array.Empty<string>()); return true;
                case "combat-setup.wander.prepare": registration = new FrameBindingRegistration("combat-setup.wander.prepare","WanderRoam",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.WanderRoam"},Array.Empty<string>()); return true;
                case "combat-setup.wander.update": registration = new FrameBindingRegistration("combat-setup.wander.update","WanderRoam",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.WanderRoam"},Array.Empty<string>()); return true;
                case "ai.magnetize.update": registration = new FrameBindingRegistration("ai.magnetize.update","Magnetize",FramePhaseMask.Wave,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","registration.Magnetize"},Array.Empty<string>()); return true;
                case "ai.sapper.prepare": registration = new FrameBindingRegistration("ai.sapper.prepare","Sapper",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","registration.Sapper"},Array.Empty<string>()); return true;
                case "ai.sapper.update": registration = new FrameBindingRegistration("ai.sapper.update","Sapper",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Sapper"},Array.Empty<string>()); return true;
                case "ai.sapper.recompute": registration = new FrameBindingRegistration("ai.sapper.recompute","Sapper",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Sapper"},Array.Empty<string>()); return true;
                case "skill-buff.wisp.update": registration = new FrameBindingRegistration("skill-buff.wisp.update","Wisp",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Wisp"},Array.Empty<string>()); return true;
                case "combat.pickup.update": registration = new FrameBindingRegistration("combat.pickup.update","Pickup",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","registration.Pickup"},Array.Empty<string>()); return true;
                case "frame.input.publish": registration = new FrameBindingRegistration("frame.input.publish","FrameScheduler",FramePhaseMask.All,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "frame.begin": registration = new FrameBindingRegistration("frame.begin","FrameScheduler",FramePhaseMask.All,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "frame.invulnerability.update": registration = new FrameBindingRegistration("frame.invulnerability.update","FrameScheduler",FramePhaseMask.All,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "frame.phaser.update": registration = new FrameBindingRegistration("frame.phaser.update","FrameScheduler",FramePhaseMask.All,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "frame.blinker.update": registration = new FrameBindingRegistration("frame.blinker.update","FrameScheduler",FramePhaseMask.All,FrameExecutionSemantics.SerialUpdate,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "frame.time.freeze": registration = new FrameBindingRegistration("frame.time.freeze","FrameScheduler",FramePhaseMask.All,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "attribute.aggregate": registration = new FrameBindingRegistration("attribute.aggregate","FrameScheduler",FramePhaseMask.All,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "build.effect.tick.real": registration = new FrameBindingRegistration("build.effect.tick.real","FrameScheduler",FramePhaseMask.Build,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "build.effect.tick.global": registration = new FrameBindingRegistration("build.effect.tick.global","FrameScheduler",FramePhaseMask.Build,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "build.effect.tick": registration = new FrameBindingRegistration("build.effect.tick","FrameScheduler",FramePhaseMask.Build,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "build.damage.commit": registration = new FrameBindingRegistration("build.damage.commit","FrameScheduler",FramePhaseMask.Build,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "build.resource.commit": registration = new FrameBindingRegistration("build.resource.commit","FrameScheduler",FramePhaseMask.Build,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "build.gameplay-event.commit": registration = new FrameBindingRegistration("build.gameplay-event.commit","FrameScheduler",FramePhaseMask.Build,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "build.ability.reject": registration = new FrameBindingRegistration("build.ability.reject","FrameScheduler",FramePhaseMask.Build,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "build.frame.close": registration = new FrameBindingRegistration("build.frame.close","FrameScheduler",FramePhaseMask.Build,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "non-wave.damage.reject": registration = new FrameBindingRegistration("non-wave.damage.reject","FrameScheduler",(FramePhaseMask.All&~(FramePhaseMask.Build|FramePhaseMask.Wave)),FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "non-wave.ability.reject": registration = new FrameBindingRegistration("non-wave.ability.reject","FrameScheduler",(FramePhaseMask.All&~(FramePhaseMask.Build|FramePhaseMask.Wave)),FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "non-wave.frame.close": registration = new FrameBindingRegistration("non-wave.frame.close","FrameScheduler",(FramePhaseMask.All&~(FramePhaseMask.Build|FramePhaseMask.Wave)),FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "movement.presentation.commit": registration = new FrameBindingRegistration("movement.presentation.commit","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.PresentationCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "threat.aggregate": registration = new FrameBindingRegistration("threat.aggregate","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "wave.frame.close": registration = new FrameBindingRegistration("wave.frame.close","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "early.damage.commit": registration = new FrameBindingRegistration("early.damage.commit","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "early.resource.commit": registration = new FrameBindingRegistration("early.resource.commit","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "spatial.index.rebuild": registration = new FrameBindingRegistration("spatial.index.rebuild","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "effect.tick": registration = new FrameBindingRegistration("effect.tick","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "effect.tick.combat": registration = new FrameBindingRegistration("effect.tick.combat","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "effect.tick.enemy": registration = new FrameBindingRegistration("effect.tick.enemy","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "effect.tick.real": registration = new FrameBindingRegistration("effect.tick.real","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "effect.tick.global": registration = new FrameBindingRegistration("effect.tick.global","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "damage.commit": registration = new FrameBindingRegistration("damage.commit","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "resource.commit": registration = new FrameBindingRegistration("resource.commit","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "gameplay-event.commit": registration = new FrameBindingRegistration("gameplay-event.commit","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "primary-death.resolve": registration = new FrameBindingRegistration("primary-death.resolve","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "primary-death.callback-dispatch": registration = new FrameBindingRegistration("primary-death.callback-dispatch","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "cascade.damage.commit": registration = new FrameBindingRegistration("cascade.damage.commit","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "cascade.resource.commit": registration = new FrameBindingRegistration("cascade.resource.commit","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "cascade-death.resolve": registration = new FrameBindingRegistration("cascade-death.resolve","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialPrepare,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "cascade-death.callback-dispatch": registration = new FrameBindingRegistration("cascade-death.callback-dispatch","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                case "post-death.gameplay-event.commit": registration = new FrameBindingRegistration("post-death.gameplay-event.commit","FrameScheduler",FramePhaseMask.Wave,FrameExecutionSemantics.SerialCommit,new[]{"ComponentStore","BattleSystemECS.Core.FrameScheduler"},Array.Empty<string>()); return true;
                default:
                    for (int i = 0; i < DisabledNodeIds.Length; i++)
                        if (string.Equals(DisabledNodeIds[i], nodeId, StringComparison.Ordinal))
                        {
                            registration = new FrameBindingRegistration(nodeId, "disabled." + nodeId, FramePhaseMask.All, FrameExecutionSemantics.SerialUpdate, new[] { "ComponentStore" }, Array.Empty<string>());
                            return true;
                        }
                    registration = default(FrameBindingRegistration); return false;
            }
        }
    }
}
